apiVersion : skaffold/v2alpha3
kind : Config
deploy : 
  kubectl : 
    manifests : 
      - ./infra/k8s/*
build : 
  # local :
  #   push : false 
  googleCloudBuild : 
    projectId : ticketing-dev-400308
  artifacts : 
    - image : us.gcr.io/ticketing-dev-400308/auth
      context : auth 
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual :
          - src : 'src/**/*.ts'
            dest : .
    - image: us.gcr.io/ticketing-dev-400308/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image : us.gcr.io/ticketing-dev-400308/tickets
      context : ticketing
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual :
          - src : 'src/**/*.ts'
            dest : .
    - image : us.gcr.io/ticketing-dev-400308/orders
      context : orders
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual :
          - src : 'src/**/*.ts'
            dest : .
    - image : us.gcr.io/ticketing-dev-400308/expiration
      context : expiration
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual :
          - src : 'src/**/*.ts'
            dest : .
    - image : us.gcr.io/ticketing-dev-400308/payments
      context : payments
      docker : 
        dockerfile : Dockerfile
      sync : 
        manual :
          - src : 'src/**/*.ts'
            dest : .

